name: MattBallek
favicon: null
layout_spectrum: 0.8362551280297339
typography_spectrum: 0.8773747843224555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282433'
    - '#ffa808'
    - '#fb3d63'
    - '#008be3'
    - '#6dbef2'
  brandStrength: 0.375
  lightness: 0.5280112696345896
  saturation: 0.23262473265640438
  rhythmicContrast: 0.8168491970282048
purpose: []
